import os
os.system("sudo apt update")
os.system("sudo apt -y upgrade")
os.system("python3 -V")
os.system("sudo apt install -y python3-pip")
os.system("pip install numpy")
os.system("pip install pandas")
os.system("pip install pandas-ta")
os.system("pip install psutil")
os.system("pip install python-binance")